-- in a real project you would put test-data in src/test/resources/db/migration but master-data could be inserted here...

INSERT INTO TASK_LIST (ID, VERSION, TITLE) VALUES (1, 0, 'Shopping List');
INSERT INTO TASK_LIST (ID, VERSION, TITLE) VALUES (2, 0, 'DIY Store List');
INSERT INTO TASK_LIST (ID, VERSION, TITLE) VALUES (3, 0, 'Holiday List');
INSERT INTO TASK_LIST (ID, VERSION, TITLE) VALUES (4, 0, 'Xmas Present List');

INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (11, 0, 1, 'Milk', false, true, null);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (12, 0, 1, 'Butter', false, true, null);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (13, 0, 1, 'Bread', false, true, null);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (14, 0, 1, 'Honey', false, false, null);

INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (21, 0, 2, 'Jigsaw', false, true, null);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (22, 0, 2, 'Paste', false, false, null);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (23, 0, 2, 'Super-Glue', true, true, null);

INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (31, 0, 3, 'Sunscreen', false, true, null);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (32, 0, 3, 'Swimsuit', false, true, null);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (33, 0, 3, 'Wetsuit', false, true, null);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (34, 0, 3, 'Flip-flops', false, true, null);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (35, 0, 3, 'Surfboard', false, true, null);

INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (41, 0, 4, 'Diamond ring', false, true, '2022-12-22 12:00'::timestamp);
INSERT INTO TASK_ITEM (ID, VERSION, LIST_ID, TITLE, COMPLETED, STARRED, DEADLINE) VALUES (42, 0, 4, 'Lingerie', true, true, '2022-12-22 12:00'::timestamp);
