CREATE TABLE TASK_LIST (
  ID                      BIGINT NOT NULL,
  VERSION                 INT NOT NULL,
  TITLE                   VARCHAR(64) NOT NULL,
  CONSTRAINT PK_TASK_LIST PRIMARY KEY (ID)
)