CREATE TABLE "TASK_ITEM" (
  ID                      NUMBER(19) NOT NULL,
  VERSION                 NUMBER(19) NOT NULL,
  TITLE                   VARCHAR(64) NOT NULL,
  DEADLINE                TIMESTAMP,
  LIST_ID            NUMBER(19),
  CONSTRAINT PK_TASK_ITEM PRIMARY KEY (ID),
  CONSTRAINT FK_ITEM_LIST FOREIGN KEY (LIST_ID) REFERENCES TASK_LIST(ID)
)